### ISSUE TITLE
VIPER - clean architecture??

### ISSUE THREAD

**Issue by Pikdays** [Nibelungc/MusicPlayer#1]
I found that there are a lot of bug, do not know did you find?

**Comment by Pikdays** [comment]
@Nibelungc

**Comment by Nibelungc** [comment]
The project is in progress, and it is my attempt to implement VIPER. But now I don't have enough time to do it appropriately. VIPER takes a lot of time :)

**Comment by Pikdays** [comment]
Ah, want to exchange ideas with you, whether you have time to write a simple example (for example: login), with optimized VIPER model, as an example template. You might ask why you own a vain handwriting

**Comment by Pikdays** [comment]
@Nibelungc

**Comment by Nibelungc** [comment]
To be fair, for me VIPER is overkill by now. Maybe I'll look at it again, later. For example you can check this project https://github.com/rambler-ios/RamblerConferences

**Comment by Pikdays** [comment]
Thank you
